# Generated by Django 3.2 on 2022-04-21 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='rating',
        ),
    ]
