# Generated by Django 3.2 on 2022-04-22 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_remove_destination_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='area_name',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='dest_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='district_name',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='dest_name',
            new_name='name',
        ),
    ]
