# Generated by Django 3.2 on 2022-05-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_rename_area_name_district_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='friendly_area_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='district',
            name='friendly_district_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
