# Generated by Django 3.2 on 2022-05-11 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0005_auto_20220508_2059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['district_name']},
        ),
        migrations.AlterField(
            model_name='destination',
            name='district',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='destinations.district'),
        ),
    ]
