# Generated by Django 3.2 on 2022-05-04 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20220504_2102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='dest_name',
            new_name='destination',
        ),
    ]
